In [1]:
import numpy as np

In [2]:
np.__version__

'1.24.4'

In [3]:
list_of_numbers = [5, 23, 25, 28, 4586]

In [4]:
vector = np.array(list_of_numbers)

In [5]:
vector

array([   5,   23,   25,   28, 4586])

In [6]:
list_of_numbers

[5, 23, 25, 28, 4586]

In [7]:
vector.shape

(5,)

In [8]:
np.array([1, 3, 6, 8, 4567]) + [5, 7, 8, 7, 456]

array([   6,   10,   14,   15, 5023])

In [9]:
import timeit

In [10]:
# kod inicjalizujacy
setup_code = """
result = []
l1 = list(range(1100, 1150))
l2 = list(range(500, 550))
"""

# kod wlasciwy
code = """
for item in zip(l1, l2):
    result.append(item[0] + item[1]) 
"""

timeit.timeit(code, setup=setup_code)

6.237728799999999

In [14]:


l1 = list(range(1100, 1150))
l2 = list(range(500, 550))



In [15]:
%%timeit

result = []
for item in zip(l1, l2):
    result.append(item[0] + item[1])

5.8 µs ± 53.1 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [16]:
%%timeit

n1 = np.array(range(1100, 1150))
n2 = np.array(range(500, 550))


result = n1 + n2 




8.57 µs ± 117 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [17]:
vector

array([   5,   23,   25,   28, 4586])

In [19]:
first_vector = np.arange(1, 6)
second_vector = np.array([1, 2, 3, 4, 5])

In [20]:
summation = first_vector + second_vector
summation

array([ 2,  4,  6,  8, 10])

In [21]:
third_vector = np.arange(1, 7)

In [22]:
summation_2 = second_vector + third_vector

ValueError: operands could not be broadcast together with shapes (5,) (6,) 

In [24]:
fourth_vector = np.array([4])

result = second_vector + fourth_vector
result

array([5, 6, 7, 8, 9])