In [1]:
import numpy as np

In [5]:
my_list = [
    [1, 2, 3, 4], 
    [5, 6, 7, 8], 
    [9, 10, 11, 12]
]

my_first_matrix = np.array(my_list)
my_first_matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
my_first_matrix.tolist()

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [11]:
my_first_matrix[2] = np.array([5, 4, 3, 2])
my_first_matrix

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 4, 3, 2]])

# dostep do kolumny

In [14]:
# drugi sposob na wyciaganie elementow macierzy
my_first_matrix[[0, 1, 2], 0]

array([1, 5, 5])

In [15]:
my_first_matrix.ndim

2

In [29]:
vector = np.arange(4)
vector.ndim
vector

array([0, 1, 2, 3])

In [19]:
my_first_matrix.dtype

dtype('int32')

In [22]:
my_first_matrix.size

12

In [23]:
my_first_matrix.shape

(3, 4)

In [30]:
vecor_kol = vector[:, np.newaxis]
vecor_kol

array([[0],
       [1],
       [2],
       [3]])

In [36]:
vector[np.newaxis, :]

array([[0, 1, 2, 3]])

In [34]:
vecor_kol.shape

(4, 1)

In [35]:
vector.shape

(4,)

In [39]:
vector_100 = np.arange(1, 101)
vector_100

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [43]:
vector_100.reshape(10, 10)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [47]:
vector_100 = vector_100.reshape(20, -1)

In [48]:
vector_100

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100]])

In [54]:
vector_flat = vector_100.flatten

print(vector_flat)

<built-in method flatten of numpy.ndarray object at 0x00000192F4759870>


In [55]:
np.zeros((2,5,6,7))

array([[[[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0.],
         [0., 0.,

In [57]:
matrix = np.array([[7,8,7,8], [4,5,6,8,], [-1,2,5,-9]])
matrix

array([[ 7,  8,  7,  8],
       [ 4,  5,  6,  8],
       [-1,  2,  5, -9]])

In [58]:
matrix.sum()

50

In [59]:
matrix.sum(axis=1)

array([30, 23, -3])

In [60]:
matrix.sum(axis=0)

array([10, 15, 18,  7])

In [61]:
matrix.mean(axis=1)

array([ 7.5 ,  5.75, -0.75])

In [62]:
matrix.mean(axis=0)

array([3.33333333, 5.        , 6.        , 2.33333333])

In [64]:
# boolean
boolean_vector = np.array([True, False, True, True])
boolean_vector.dtype

dtype('bool')

In [66]:
boolean_matrix = boolean_vector.reshape(2, -1)
boolean_matrix

array([[ True, False],
       [ True,  True]])

In [67]:
matrix = np.arange(10).reshape(2,5)
matrix

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [70]:
bool_matrix = matrix > 5
bool_matrix

array([[False, False, False, False, False],
       [False,  True,  True,  True,  True]])

In [72]:
matrix[matrix > 5]

array([6, 7, 8, 9])

In [73]:
# NaN
np.nan

nan

In [76]:
rain = np.array([2, 10, 9, 5, np.nan])
rain

array([ 2., 10.,  9.,  5., nan])

In [78]:
~np.isnan(rain)

array([ True,  True,  True,  True, False])

In [79]:
np.isnan(rain)

array([False, False, False, False,  True])